### ISSUE TITLE
Add hover effect in Navbar

### ISSUE THREAD

**Issue by Srijita-Mandal** [GDSCCGEC/gdsc-cgec#2]
![navbar](https://user-images.githubusercontent.com/84610348/200052111-a161c8da-2e14-4283-955c-7135114d2370.png)
1.Add some hover effect in navbar menus: HOME, ABOUT, EVENTS, TEAM, CONTACT
2. Only add css in ```style.css```
3. Please don't change navbar code.

Contact for any doubt or query.

**Comment by Ritu-2001** [comment]
assign me for it
