### ISSUE TITLE
Create footer

### ISSUE THREAD

**Issue by Srijita-Mandal** [GDSCCGEC/gdsc-cgec#3]
![footer](https://user-images.githubusercontent.com/84610348/200052634-4d26d320-7dc9-41f2-9e60-7fbf768e2b1c.png)
1. Create this footer
2. Add your code in ```index.html``` file
3. Use Bootstrap 4 version (if needed).
4. All items are linked. Add all items in footer in ```<a></a>``` tag
5. Use ```font-family: 'Poppins',sans-serif;```
6. Use ```#101B26``` for background color.
7. Make it responsive.

Contact for any doubt or query.

**Comment by Ritu-2001** [comment]
Assign me for this issue

**Comment by Subrata-Rajak** [comment]
@Srijita-Mandal Keep a credit section in the footer like who developed, who designed, who provided the content etc.

**Comment by Srijita-Mandal** [comment]
> @Srijita-Mandal Keep a credit section in the footer like who developed, who designed, who provided the content etc.

Okay
